version: '3.8'

services:
  rust-app:
    build:
      context: . # Use the current directory as the build context
    ports:
      - 8080:8080
    environment:
      TEST_CONFIG_PATH: /app/config.toml
      RUST_LOG: debug
    volumes:
      - ./config.toml:/app/config.toml
    
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "nobody"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      # - '--web.external-url=/prometheus/'
      # - '--web.route-prefix=/prometheus/'
      # /!\ Uncomment the following line to set a size limit for the Prometheus database /!\
#      - '--storage.tsdb.retention.size=10GB'
    expose:
      - 9090
    volumes:
      # /!\ To be modified depending on your needs /!\
      - ./prometheus/data:/prometheus
      - ./prometheus:/etc/prometheus/
      
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/.env
    volumes:
      # /!\ To be modified depending on your needs /!\
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      
